# Business Data EDA

In [1]:
%matplotlib inline
import numpy as np
import math
import matplotlib.pyplot as plt
import pandas as pd
import datetime
from glob import glob

import seaborn as sns
sns.set_style('whitegrid')
sns.set_context("poster")

In [2]:
def time_marker(text=''):
    print('[{}] {}'.format(datetime.datetime.now().time(), text))

In [3]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))

import matplotlib
font = {'size' : 50}
matplotlib.rc('font', **font)

TITLE_FONT_SIZE = 25
LABEL_FONT_SIZE = 15
TICK_FONT_SIZE  = 15

day_labels = ['MON','TUE','WED','THU','FRI','SAT','SUN']
day_labels_full = ['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY']
month_labels = ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC']
month_labels_full = ['JANUARY','FEBRUARY','MARCH','APRIL','MAY','JUNE','JULY','AUGUST','SEPTEMBER','OCTOBER','NOVEMBER','DECEMBER']

FIG_SIZE = (15,6)
FIG_SIZE_SHORT = (15,3)
GRID_DIMS = 15

DO_WRITE_CHARTS = False

# Load Review Data

In [4]:
time_marker(text='Loading Review Data...')

business = pd.DataFrame()
file_path_slug = '../clean_data/business/*.csv'
file_list = glob(file_path_slug)


# Chunk Settings
chunks = list()
chunksize = 10000
newest_review_date = pd.Timestamp('2017-07-26')

for ii, file in enumerate(file_list):
    time_marker('Reading {} of {} {}...'.format(ii+1, len(file_list), file))
    num_chunks = math.ceil(sum(1 for row in open(file, 'r'))/chunksize)
    format_width = len(str(num_chunks))

    # import file in chunks
    for jj, chunk in enumerate(pd.read_csv(file, chunksize=chunksize, iterator=True, index_col=0)):

        # append chunk to chunks list
        chunks.append(chunk)        
        
        if jj % 10 == 0 or jj == num_chunks:
            time_marker(text='\tfinished chunk {} of {}'.format(str(jj+1).rjust(format_width), str(num_chunks).rjust(format_width)))

time_marker(text='merging to dataframe...')
business = pd.concat(chunks)

time_marker('reseting index...')
business.reset_index(inplace=True, drop=True)
time_marker(text='Complete!')

[22:28:17.617711] Loading Review Data...
[22:28:17.621964] Reading 1 of 64 ../clean_data/business/07_6_business_clean.csv...

/Users/samgutentag/anaconda/envs/spring/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (28,60,61,62,63,64,65,66) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

[22:28:18.402027] 	finished chunk 1 of 1
[22:28:18.402438] Reading 2 of 64 ../clean_data/business/26_P_business_clean.csv...

/Users/samgutentag/anaconda/envs/spring/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (28,60,61,62,63,64,65,66,77,78,84) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

[22:28:19.121854] 	finished chunk 1 of 1
[22:28:19.122150] Reading 3 of 64 ../clean_data/business/33_W_business_clean.csv...

/Users/samgutentag/anaconda/envs/spring/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (60,61,62,63,64,65,66) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

[22:28:19.804177] 	finished chunk 1 of 1
[22:28:19.804507] Reading 4 of 64 ../clean_data/business/24_N_business_clean.csv...
[22:28:20.481309] 	finished chunk 1 of 1
[22:28:20.481581] Reading 5 of 64 ../clean_data/business/36_Z_business_clean.csv...
[22:28:21.176895] 	finished chunk 1 of 1
[22:28:21.177141] Reading 6 of 64 ../clean_data/business/49_l_business_clean.csv...

/Users/samgutentag/anaconda/envs/spring/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (28,40,60,61,62,63,64,65,66) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

[22:28:21.852362] 	finished chunk 1 of 1
[22:28:21.852615] Reading 7 of 64 ../clean_data/business/13_C_business_clean.csv...
[22:28:22.565864] 	finished chunk 1 of 1
[22:28:22.566112] Reading 8 of 64 ../clean_data/business/57_t_business_clean.csv...
[22:28:23.347932] 	finished chunk 1 of 1
[22:28:23.348158] Reading 9 of 64 ../clean_data/business/29_S_business_clean.csv...
[22:28:24.191732] 	finished chunk 1 of 1
[22:28:24.191964] Reading 10 of 64 ../clean_data/business/18_H_business_clean.csv...
[22:28:24.851707] 	finished chunk 1 of 1
[22:28:24.851972] Reading 11 of 64 ../clean_data/business/22_L_business_clean.csv...
[22:28:25.579349] 	finished chunk 1 of 1
[22:28:25.579646] Reading 12 of 64 ../clean_data/business/14_D_business_clean.csv...
[22:28:26.289870] 	finished chunk 1 of 1
[22:28:26.290166] Reading 13 of 64 ../clean_data/business/47_j_business_clean.csv...
[22:28:27.190260] 	finished chunk 1 of 1
[22:28:27.190494] Reading 14 of 64 ../clean_data/business/40_c_business_clean.csv...
[22:28:27.855667] 	finished chunk 1 of 1
[22:28:27.855900] Reading 15 of 64 ../clean_data/business/60_w_business_clean.csv...
[22:28:28.518898] 	finished chunk 1 of 1
[22:28:28.519216] Reading 16 of 64 ../clean_data/business/46_i_business_clean.csv...
[22:28:29.186269] 	finished chunk 1 of 1
[22:28:29.186544] Reading 17 of 64 ../clean_data/business/00_-_business_clean.csv...
[22:28:29.851100] 	finished chunk 1 of 1
[22:28:29.851338] Reading 18 of 64 ../clean_data/business/21_K_business_clean.csv...
[22:28:30.492246] 	finished chunk 1 of 1
[22:28:30.492502] Reading 19 of 64 ../clean_data/business/45_h_business_clean.csv...
[22:28:31.196563] 	finished chunk 1 of 1
[22:28:31.196794] Reading 20 of 64 ../clean_data/business/16_F_business_clean.csv...

/Users/samgutentag/anaconda/envs/spring/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (28,60,61,62,63,64,65,66,77,78,79,80,81,82,83,84) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

[22:28:31.996791] 	finished chunk 1 of 1
[22:28:31.997029] Reading 21 of 64 ../clean_data/business/11_A_business_clean.csv...
[22:28:32.710243] 	finished chunk 1 of 1
[22:28:32.710464] Reading 22 of 64 ../clean_data/business/06_5_business_clean.csv...
[22:28:33.424012] 	finished chunk 1 of 1
[22:28:33.424260] Reading 23 of 64 ../clean_data/business/09_8_business_clean.csv...
[22:28:34.090695] 	finished chunk 1 of 1
[22:28:34.090941] Reading 24 of 64 ../clean_data/business/34_X_business_clean.csv...
[22:28:34.756300] 	finished chunk 1 of 1
[22:28:34.756547] Reading 25 of 64 ../clean_data/business/31_U_business_clean.csv...
[22:28:35.393763] 	finished chunk 1 of 1
[22:28:35.394008] Reading 26 of 64 ../clean_data/business/05_4_business_clean.csv...
[22:28:36.059316] 	finished chunk 1 of 1
[22:28:36.059637] Reading 27 of 64 ../clean_data/business/50_m_business_clean.csv...
[22:28:36.705764] 	finished chunk 1 of 1
[22:28:36.706012] Reading 28 of 64 ../clean_data/business/59_v_business_clean.csv...
[22:28:37.388297] 	finished chunk 1 of 1
[22:28:37.388544] Reading 29 of 64 ../clean_data/business/01_0_business_clean.csv...
[22:28:38.039870] 	finished chunk 1 of 1
[22:28:38.040118] Reading 30 of 64 ../clean_data/business/37___business_clean.csv...
[22:28:38.700990] 	finished chunk 1 of 1
[22:28:38.701224] Reading 31 of 64 ../clean_data/business/15_E_business_clean.csv...
[22:28:39.364741] 	finished chunk 1 of 1
[22:28:39.365013] Reading 32 of 64 ../clean_data/business/02_1_business_clean.csv...
[22:28:39.987826] 	finished chunk 1 of 1
[22:28:39.988072] Reading 33 of 64 ../clean_data/business/23_M_business_clean.csv...

/Users/samgutentag/anaconda/envs/spring/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

[22:28:40.646639] 	finished chunk 1 of 1
[22:28:40.646880] Reading 34 of 64 ../clean_data/business/19_I_business_clean.csv...
[22:28:41.301493] 	finished chunk 1 of 1
[22:28:41.301788] Reading 35 of 64 ../clean_data/business/43_f_business_clean.csv...
[22:28:41.950129] 	finished chunk 1 of 1
[22:28:41.950380] Reading 36 of 64 ../clean_data/business/28_R_business_clean.csv...
[22:28:42.582427] 	finished chunk 1 of 1
[22:28:42.583483] Reading 37 of 64 ../clean_data/business/38_a_business_clean.csv...
[22:28:43.272227] 	finished chunk 1 of 1
[22:28:43.272473] Reading 38 of 64 ../clean_data/business/54_q_business_clean.csv...
[22:28:43.896352] 	finished chunk 1 of 1
[22:28:43.896597] Reading 39 of 64 ../clean_data/business/12_B_business_clean.csv...
[22:28:44.543347] 	finished chunk 1 of 1
[22:28:44.543601] Reading 40 of 64 ../clean_data/business/62_y_business_clean.csv...
[22:28:45.214904] 	finished chunk 1 of 1
[22:28:45.215146] Reading 41 of 64 ../clean_data/business/04_3_business_clean.csv...
[22:28:45.859942] 	finished chunk 1 of 1
[22:28:45.860186] Reading 42 of 64 ../clean_data/business/25_O_business_clean.csv...
[22:28:46.525618] 	finished chunk 1 of 1
[22:28:46.525868] Reading 43 of 64 ../clean_data/business/32_V_business_clean.csv...
[22:28:47.177444] 	finished chunk 1 of 1
[22:28:47.177692] Reading 44 of 64 ../clean_data/business/27_Q_business_clean.csv...
[22:28:47.832253] 	finished chunk 1 of 1
[22:28:47.832500] Reading 45 of 64 ../clean_data/business/61_x_business_clean.csv...
[22:28:48.552554] 	finished chunk 1 of 1
[22:28:48.552866] Reading 46 of 64 ../clean_data/business/55_r_business_clean.csv...
[22:28:49.207783] 	finished chunk 1 of 1
[22:28:49.208016] Reading 47 of 64 ../clean_data/business/63_z_business_clean.csv...
[22:28:49.975456] 	finished chunk 1 of 1
[22:28:49.975700] Reading 48 of 64 ../clean_data/business/30_T_business_clean.csv...
[22:28:50.655368] 	finished chunk 1 of 1
[22:28:50.655593] Reading 49 of 64 ../clean_data/business/39_b_business_clean.csv...
[22:28:51.561981] 	finished chunk 1 of 1
[22:28:51.562231] Reading 50 of 64 ../clean_data/business/35_Y_business_clean.csv...
[22:28:52.247667] 	finished chunk 1 of 1
[22:28:52.247900] Reading 51 of 64 ../clean_data/business/56_s_business_clean.csv...
[22:28:53.207281] 	finished chunk 1 of 1
[22:28:53.207656] Reading 52 of 64 ../clean_data/business/44_g_business_clean.csv...
[22:28:53.869206] 	finished chunk 1 of 1
[22:28:53.869454] Reading 53 of 64 ../clean_data/business/48_k_business_clean.csv...
[22:28:54.588322] 	finished chunk 1 of 1
[22:28:54.588559] Reading 54 of 64 ../clean_data/business/53_p_business_clean.csv...
[22:28:55.300875] 	finished chunk 1 of 1
[22:28:55.301119] Reading 55 of 64 ../clean_data/business/10_9_business_clean.csv...
[22:28:56.005114] 	finished chunk 1 of 1
[22:28:56.005347] Reading 56 of 64 ../clean_data/business/41_d_business_clean.csv...
[22:28:56.760405] 	finished chunk 1 of 1
[22:28:56.760720] Reading 57 of 64 ../clean_data/business/17_G_business_clean.csv...
[22:28:57.425226] 	finished chunk 1 of 1
[22:28:57.425479] Reading 58 of 64 ../clean_data/business/51_n_business_clean.csv...

/Users/samgutentag/anaconda/envs/spring/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (60,61,62,63,64,65,66,77,78,84) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

[22:28:58.293903] 	finished chunk 1 of 1
[22:28:58.294146] Reading 59 of 64 ../clean_data/business/58_u_business_clean.csv...
[22:28:59.035078] 	finished chunk 1 of 1
[22:28:59.035386] Reading 60 of 64 ../clean_data/business/20_J_business_clean.csv...
[22:28:59.728465] 	finished chunk 1 of 1
[22:28:59.728714] Reading 61 of 64 ../clean_data/business/42_e_business_clean.csv...
[22:29:00.405198] 	finished chunk 1 of 1
[22:29:00.405454] Reading 62 of 64 ../clean_data/business/08_7_business_clean.csv...
[22:29:01.109628] 	finished chunk 1 of 1
[22:29:01.109892] Reading 63 of 64 ../clean_data/business/03_2_business_clean.csv...
[22:29:01.925841] 	finished chunk 1 of 1
[22:29:01.927391] Reading 64 of 64 ../clean_data/business/52_o_business_clean.csv...
[22:29:02.614377] 	finished chunk 1 of 1
[22:29:02.614693] merging to dataframe...
[22:29:10.339327] reseting index...
[22:29:10.342177] Complete!

In [5]:
business.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156639 entries, 0 to 156638
Columns: 1347 entries, business_id to zoos
dtypes: float64(28), int64(1242), object(77)
memory usage: 1.6+ GB

## Manually selected list of all Restaurant, Bar, and Eatery columns

In [6]:
food_cols = ['acai_bowls', 'afghan', 'african', 'alsatian', 'american_(new)', 'american_(traditional)', 'arabian', 'argentine', 'armenian', 
             'asian_fusion', 'australian', 'austrian', 'ayurveda', 'baden', 'bagels', 'bakeries', 'bangladeshi', 
             'barbeque', 'bars', 'bavarian', 'beach_bars', 'bed_&_breakfast', 'beer', 'beer_bar', 'beer_garden', 
             'beer_gardens', 'beer_hall', 'belgian', 'bistros', 'brazilian', 'breakfast_&_brunch', 'breweries', 
             'british', 'bubble_tea', 'buffets', 'bulgarian', 'burgers', 'burmese', 'cajun/creole', 'canadian_(new)', 'cambodian', 
             'cantonese', 'caribbean', 'champagne_bars', 'cheese_shops', 'cheesesteaks', 'chicken_wings', 'chinese', 
             'chocolatiers_&_shops', 'cocktail_bars', 'coffee_&_tea', 'coffee_roasteries', 'coffeeshops', 'colombian', 
             'comfort_food', 'creperies', 'cuban', 'cupcakes', 'curry_sausage', 'czech', 'czech/slovakian', 
             'delicatessen', 'delis', 'desserts', 'dim_sum', 'diners', 'dive_bars', 'dominican', 'donuts', 
             'eastern_european', 'eastern_german', 'egyptian', 'empanadas', 'ethiopian', 'ethnic_food', 'falafel', 
             'fast_food', 'filipino', 'fischbroetchen', 'fish_&_chips', 'flatbread', 'fondue', 'food_court', 
             'food_stands', 'food_tours', 'food_trucks', 'french', 'friterie', 'gastropubs', 'gelato', 'georgian', 
             'german', 'gluten-free', 'greek', 'guamanian', 'hainan', 'haitian', 'hakka', 'halal', 'hawaiian', 
             'himalayan/nepalese', 'honduran', 'hong_kong_style_cafe', 'hot_dogs', 'hot_pot', 'hungarian', 'iberian', 
             'indian', 'indonesian', 'irish', 'irish_pub', 'island_pub', 'italian', 'izakaya', 'japanese', 'japanese_curry', 
             'juice_bars_&_smoothies', 'kebab', 'kombucha', 'korean', 'kosher', 'laotian', 'latin_american', 
             'lebanese', 'local_flavor', 'macarons', 'malaysian', 'mauritius', 'mediterranean', 'mexican', 
             'middle_eastern', 'milkshake_bars', 'minho', 'modern_european', 'mongolian', 'moroccan', 'muay_thai', 
             'new_mexican_cuisine', 'nicaraguan', 'noodles', 'olive_oil', 'oriental', 'paint_&_sip', 'pakistani', 
             'palatine', 'pan_asian', 'pasta_shops', 'patisserie/cake_shop', 'persian/iranian', 'peruvian', 'piano_bars', 
             'pita', 'pizza', 'poke', 'polish', 'pop-up_restaurants', 'popcorn_shops', 'portuguese', 'poutineries', 
             'pretzels', 'pub_food', 'pubs', 'puerto_rican', 'ramen', 'restaurants', 'rotisserie_chicken', 'russian', 
             'salad', 'salvadoran', 'sandwiches', 'scandinavian', 'scottish', 'seafood', 'senegalese', 'serbo_croatian', 
             'shanghainese', 'shaved_ice', 'singaporean', 'slovakian', 'soba', 'soul_food', 'soup', 'south_african', 
             'southern', 'spanish', 'speakeasies', 'specialty_food', 'sports_bars', 'sri_lankan', 'steakhouses', 
             'sugar_shacks', 'sushi_bars', 'swabian', 'swiss_food', 'syrian', 'szechuan', 'tacos', 'taiwanese', 
             'tapas_bars', 'tapas/small_plates', 'tea_rooms', 'tempura', 'teppanyaki', 'tex-mex', 'thai', 'themed_cafes', 
             'tiki_bars', 'tonkatsu', 'turkish', 'tuscan', 'udon', 'ukrainian', 'uzbek', 'vegan', 'vegetarian', 
             'venezuelan', 'vietnamese', 'waffles', 'whiskey_bars', 'wine_&_spirits', 'wine_bars', 'wok', 'wraps']

# Narrow down dataframe to only food and restaurants

In [50]:
time_marker('subset businesses with food and restaurant category columns set to 1...')
food_idx = list()
for ii, col in enumerate(food_cols):
    for idx in list(business[business[col] == 1].index):
        if idx not in food_idx:
            food_idx.append(idx)

restaurants = business.iloc[food_idx,:].copy()
time_marker('done')

[23:15:17.460588] collecting list of businesses with food and restaurant category columns set to 1...
[23:17:19.160134] done

In [51]:
time_marker('collecting list of businesses with non food and restaurant category columns...')
non_food_cols = list()
for col in list(restaurants.columns):
    if col not in food_cols:
        non_food_cols.append(col)
non_food_cols = non_food_cols[107:]

[23:18:53.272225] collecting list of businesses with non food and restaurant category columns...

In [52]:
time_marker('prune businesses with non food and restaurant category columns set to 1...')
non_food_idx = list()
for ii, col in enumerate(non_food_cols):
    for idx in list(restaurants[restaurants[col] == 1].index):
        if idx not in non_food_idx:
            non_food_idx.append(idx)

restaurants = restaurants.loc[~restaurants.index.isin(non_food_idx)]
time_marker('done')

[23:19:01.083985] collecting list of businesses with non food and restaurant category columns set to 1...
[23:19:19.502268] done

In [53]:
# restaurants = business.iloc[food_selection_index,:].copy()

time_marker('dropping columns of all zeros')
restaurants = restaurants.loc[:, (restaurants != 0).any(axis=0)].copy()

time_marker('dropping columns of all nan')
restaurants.replace('NaN', np.nan, inplace=True)
restaurants.replace(' NaN', np.nan, inplace=True)
restaurants.dropna(axis=1, how='all', inplace=True)

# reset index
time_marker('resetting index...')
restaurants.reset_index(inplace=True, drop=True)
time_marker('done')

[23:19:54.089772] dropping columns of all zeros
[23:19:55.950218] dropping columns of all nan
[23:20:00.503745] resetting index...
[23:20:00.504376] done

In [54]:
print('Restaurants                {:d}'.format(restaurants.shape[0]))
print('All businesses             {:d}'.format(business.shape[0]))
print('Ratio of Restaurants       {:2.4f}'.format((restaurants.shape[0]/business.shape[0] * 100.)))

Restaurants                33497
All businesses             156639
Ratio of Restaurants       21.3848

# Write to File

In [55]:
restaurants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33497 entries, 0 to 33496
Columns: 252 entries, business_id to wraps
dtypes: float64(26), int64(158), object(68)
memory usage: 64.4+ MB

In [56]:
restaurants.head()

,business_id,address,city,is_open,latitude,longitude,name,neighborhood,postal_code,review_count,...,turkish,ukrainian,uzbek,vegan,vegetarian,venezuelan,vietnamese,waffles,wok,wraps
0,6Cl15LapBVhw4ZfBIeVJJA,"1674 N Higley Rd, Ste 104",Gilbert,0,33.381279,-111.724168,Rania's Kabob Grill,NaN,85234,320,...,0,0,0,0,0,0,0,0,0,0
1,Pi7dsdOXqrMaC53V5TOqBQ,4929 W Ray Rd,Chandler,0,33.319526,-111.925763,Zaytoon Kabob Bistro,NaN,85226,3,...,0,0,0,0,0,0,0,0,0,0
2,NCayC7-QUer-1m-UW_71Yg,1450 Kingston Road,Pickering,0,43.841453,-79.083996,Mahipar Kabab,NaN,L1V 1C1,6,...,0,0,0,0,0,0,0,0,0,0
3,NSfAp377ZRl5Mee430KTcA,17310 Yonge Street,Newmarket,1,44.050083,-79.479545,Pita & Grill,NaN,L3Y 7R8,13,...,0,0,0,0,0,0,0,0,0,0
4,ZCdXbef51G3yyjVEXB7AYw,3595 Sheppard Avenue E,Toronto,1,43.780840,-79.298867,Alanoor Afghan Kabob,Scarborough,M1T 3K8,15,...,0,0,0,0,0,0,0,0,0,0

In [62]:
time_marker('writing to file...')
restaurants.to_csv('../clean_data/_analysis/restaurants.csv', encoding=('utf-8'))
time_marker('done')

[23:21:44.524178] writing to file...
[23:21:50.240295] done

# Exploratorty Data Analysis

<p><b>1.</b> Number of restaurants in each category</p>

In [64]:
for ii, col in enumerate(restaurants.columns[96:]):
    df = restaurants[restaurants[col] == 1].copy()
    print('{} {}'.format(str(col).ljust(30), df.shape[0]))

afghan                         75
african                        88
american_(new)                 1709
american_(traditional)         2770
arabian                        38
argentine                      21
armenian                       6
asian_fusion                   1138
australian                     3
austrian                       7
baden                          1
bangladeshi                    12
barbeque                       932
bavarian                       10
beer_garden                    35
beer_hall                      2
belgian                        17
bistros                        47
brazilian                      47
breakfast_&_brunch             1936
british                        101
buffets                        639
bulgarian                      1
burgers                        2992
burmese                        8
cajun/creole                   167
cambodian                      27
canadian_(new)                 676
cantonese                      58
caribbean                      352
cheesesteaks                   138
chicken_wings                  1337
chinese                        3259
colombian                      17
comfort_food                   259
creperies                      64
cuban                          38
curry_sausage                  8
czech                          5
czech/slovakian                1
delis                          805
dim_sum                        188
diners                         861
dominican                      8
eastern_european               1
egyptian                       9
ethiopian                      51
falafel                        79
fast_food                      4819
filipino                       109
fish_&_chips                   244
flatbread                      2
fondue                         28
food_court                     75
food_stands                    89
french                         587
gastropubs                     138
georgian                       1
german                         248
gluten-free                    307
greek                          788
hainan                         1
haitian                        5
hakka                          17
halal                          295
hawaiian                       148
himalayan/nepalese             41
honduran                       3
hong_kong_style_cafe           1
hot_dogs                       455
hot_pot                        62
hungarian                      19
iberian                        2
indian                         1056
indonesian                     18
irish                          22
italian                        3148
izakaya                        3
japanese                       1871
kebab                          42
korean                         561
kosher                         71
laotian                        7
latin_american                 307
lebanese                       123
local_flavor                   116
malaysian                      55
mauritius                      1
mediterranean                  1066
mexican                        3048
middle_eastern                 734
minho                          1
modern_european                105
mongolian                      37
moroccan                       51
new_mexican_cuisine            11
nicaraguan                     2
noodles                        219
oriental                       2
pakistani                      301
palatine                       1
pan_asian                      60
persian/iranian                114
peruvian                       72
pita                           1
pizza                          4333
polish                         31
portuguese                     155
poutineries                    72
pub_food                       3
puerto_rican                   11
ramen                          117
restaurants                    33417
russian                        31
salad                          999
salvadoran                     49
sandwiches                     3465
scandinavian                   4
scottish                       32
seafood                        1321
senegalese                     1
serbo_croatian                 8
shanghainese                   8
singaporean                    10
slovakian                      2
soul_food                      157
soup                           363
south_african                  11
southern                       260
spanish                        112
sri_lankan                     17
steakhouses                    847
sushi_bars                     1575
swabian                        90
swiss_food                     2
syrian                         2
szechuan                       63
tacos                          47
taiwanese                      70
tapas_bars                     131
tapas/small_plates             135
tempura                        1
teppanyaki                     17
tex-mex                        500
thai                           1116
tonkatsu                       1
turkish                        126
ukrainian                      9
uzbek                          3
vegan                          251
vegetarian                     514
venezuelan                     12
vietnamese                     795
waffles                        27
wok                            1
wraps                          18

<p><b>2.</b> Number of open and closed restaurants</p>

In [65]:
print('Number of open restaurants   {:d}'.format(restaurants[restaurants.is_open == 1].shape[0]))
print('Number of closed restaurants {:d}'.format(restaurants[restaurants.is_open == 0].shape[0]))

Number of open restaurants   24454
Number of closed restaurants 9043

<p><b>3.</b> Unique values in non categorical columns</p>

In [68]:
# restaurants.columns[:96]
for ii, col in enumerate(restaurants.columns[:96]):
    print('{} {}\n{}'.format(str(col).ljust(30), len(restaurants[col].unique()),restaurants[col].unique()))
    print('-'*80)

business_id                    33497
['6Cl15LapBVhw4ZfBIeVJJA' 'Pi7dsdOXqrMaC53V5TOqBQ' 'NCayC7-QUer-1m-UW_71Yg'
 ..., 'oehWJ_dAlzU9C65b7zzKbQ' 'okop_ufDnpNze_l1SXOf2g'
 'oz-U184llqjVIt398hLntQ']
--------------------------------------------------------------------------------
address                        28897
['1674 N Higley Rd, Ste 104' '4929 W Ray Rd' '1450 Kingston Road' ...,
 '4th Floor, 33 Castle Street' '11729 Detroit Ave' '2155 E University Dr']
--------------------------------------------------------------------------------
city                           636
['Gilbert' 'Chandler' 'Pickering' 'Newmarket' 'Toronto' 'Mississauga'
 'Dollard-des-Ormeaux' 'Madison' 'North Olmsted' 'Las Vegas' 'Ajax'
 'Phoenix' 'Brampton' 'Vaughan' 'Pineville' 'Richmond Hill' 'Laval'
 'Montréal' 'Edinburgh' 'Mesa' 'Markham' 'East York' 'Whitby' 'Stuttgart'
 'Pittsburgh' 'Scarborough' 'Glendale' 'Charlotte' 'Montreal' 'Ludwigsburg'
 'Etobicoke' 'Champaign' 'Mercier' 'Oakville' 'Cleveland'
 'Cleveland Heights' 'Gibsonia' 'Fitchburg' 'Matthews' 'Middleburg Heights'
 'Scottsdale' 'Medina' 'Mayfield Heights' 'Eastlake' 'Sun City' 'Waxhaw'
 'Cuyahoga Falls' 'Tega Cay' 'Beachwood' 'Stanley' 'Mentor' 'Tempe'
 'Bridgeville' 'Sewickley' 'Surprise' 'Lyndhurst' 'Cornelius' 'Westlake'
 'New Kensington' 'Unionville' 'Cave Creek' 'Sun Prairie' 'Gastonia'
 'North Las Vegas' 'Homestead' 'Aurora' 'North Royalton' 'Henderson'
 'Euclid' 'Burton' 'Lorain' 'McMurray' 'Garfield Heights' 'North York'
 'Jefferson Hills' 'Stallings' 'Litchfield Park' 'Irwin' 'Avon Lake'
 'Verona' 'Concord' 'El Mirage' 'Kent' 'Fort Mill' 'Anthem' 'Streetsboro'
 'Sun City West' 'Catawba Springs' 'North Huntingdon' 'Carefree' 'Solon'
 'Glenshaw' 'Brunswick' 'Oregon' 'Chagrin Falls' 'Paradise Valley'
 'Coraopolis' 'South Euclid' 'Amherst' 'Tuscola' 'Pleasant Hills'
 'Valley View' 'Kannapolis' 'Hudson' 'Middleton' 'Huntersville' 'Cecil'
 'Bratenahl' 'Lasalle' 'Cramerton' 'De Forest' 'Painesville' 'Wexford'
 'Maple Heights' 'Boulder City' 'Willoughby' 'Belmont' 'Macedonia'
 'Monroeville' 'Mt. Lebanon' 'Oakmont' 'Ambridge' 'Stow' 'Elyria'
 'McKeesport' 'Twinsburg' 'South Gyle' 'Harrisburg' 'Bethel Park'
 'Fairview Park' "Saint-Roch-De-L'achigan" 'South Las Vegas'
 'North Versailles' 'Lakewood' 'Murrysville' 'Fountain Hills' 'Brecksville'
 'Harmarville' 'Middlefield' 'Richmond Hts' 'Willoughby Hills' 'Peoria'
 'Edgewood' 'Independence' 'Thornhill' 'Olmsted Falls' 'Turtle Creek'
 'Indian Trail' 'Cheswick' 'Laveen' 'Avondale' 'Davidson' 'Rouses Point'
 'Richfield' 'Urbana' 'Goodyear' 'Seven Hills' 'Russellton' 'Moon' 'Avon'
 'DeForest' 'Strongsville' 'Brooklyn' 'Berea' 'Mount Horeb'
 'Highland Heights' 'clinton' 'Glassport' 'Dallas' 'Canonsburg' 'LasVegas'
 'Ogden' 'Cross Plains' 'Bellevue' 'Herminie' 'Allison Park' 'Lowell'
 'Elizabeth Township' 'Tallmadge' 'Willowick' 'Oakland' 'Parma' 'Brossard'
 'Creighton' 'Sun Lakes' 'Imperial' 'Warrensville Heights'
 'Richmond Heights' 'North Ridgeville' 'Fairlawn' 'Monongahela'
 'Grand River' 'University Heights' 'Fort McDowell' 'Stoughton' 'St Joseph'
 'Westmount' 'Rocky River' 'Concord Twp' 'Monticello' 'Robinson Township'
 'Mount Holly' 'Inverness' 'Munhall' 'Gifford' 'White Oak' 'Bay Village'
 'Mint Hill' 'Tolleson' 'Scaroborough' 'Mount Lebanon' 'West Homestead'
 'Elizabeth' 'Whtiby' 'Chesterland' 'Brentwood' 'Mahomet' 'Boisbriand'
 'New Eagle' 'Youngtown' 'Hawthorne' 'Mayfield Village' 'Bainbridge'
 'Fairview' 'Georgetown' 'South Amherst' 'Dane' 'Pheonix' 'Wilmerding'
 'Dollard-Des-Ormeaux' 'Sindelfingen' 'Lachute' 'Indian Land' 'Kirkcaldy'
 'Sheffield' 'McCandless Township' 'Hendersonville' 'North Olmstead'
 'Bedford' 'Orange Village' 'Carnegie' 'Clark' 'McKees Rocks' 'Homer'
 'Brook Park' 'Northfield' 'Böblingen' 'Frazer' 'West Mifflin' 'Nottingham'
 'WICKLIFFE' 'Paoli' 'Sheffield Village' 'Verdun' 'Hampton Township'
 'Weddington' 'TORONTO' 'Ostfildern' 'Pointe-Claire' 'Springdale' 'Rantoul'
 'Philo' 'Woodbridge' 'Montrose' 'Mc Kees Rocks' 'Guadalupe' 'Trafford'
 'Library' 'West Elizabeth' 'McDonald' 'Waunakee' 'Medina Township'
 'Newhaven' 'Windsor' 'Black Earth' 'Stouffville' 'Caledon' 'Esslingen'
 'Monona' 'Mantua' 'Kirkland' 'Livingston' 'Chardon' 'Bedford Heights'
 'Rexdale' 'Clairton' 'Cottage Grove' 'Midland' 'Moon Township' 'Woodmere'
 'Emsworth' 'Neville Island' 'Copley' 'Houston' 'Finleyville'
 'Mont-Saint-Gregoire' 'Etna' 'Rillton' 'Walton Hills' 'Longueuil'
 'South Queensferry' 'Oakdale' 'East Gwillimbury' 'Newbury' 'Wickliffe'
 'Shaker Heights' 'South Park Township' 'MESA' 'Olivos' 'Saint-Laurent'
 'Fellbach' 'San Tan Valley' 'Parma Heights' 'West View' 'Chertsey'
 'Esslingen am Neckar' 'Valley City' 'Liberty' 'Lake Wylie'
 'Shaler Township' 'Orange' 'Châteauguay' 'Schwieberdingen' 'York'
 'Shadyside' 'Rosemere' 'Leonberg' 'Joliette' 'Blawnox' 'St-Leonard'
 'Saint-Hubert' 'Arnold' 'Waiblingen' 'Maple' 'Whitchurch-Stouffville'
 'Gerlingen' 'Beloeil' 'Outremont' 'Saint-Lambert' 'Quartermile'
 'Terrebonne' 'Chateauguay' 'Stetten' 'Leinfelden-Echterdingen' 'Penicuik'
 "L'Île-Perrot" 'Saint-Sauveur' 'Savoy' 'Saint-Leonard' 'Sainte-Julie'
 'Bonnyrigg' 'Bradford' 'Pierrefonds' 'Mont-Royal'
 'Sainte-Anne-de-Bellevue' 'Penn Hills' 'La Prairie' 'Lachenaie'
 'Montreal-Ouest' 'Plum' 'Mayfield' 'Spring Valley' 'Lachine' 'Denkendorf'
 'Ditzingen' 'Aichwald' 'Kornwestheim' 'Vaudreuil-Dorion' 'Lagrange'
 'Mont-Saint-Hilaire' 'Saint Laurent' 'Greenfield Park' 'Saint-Jerome'
 'Saint-Hyacinthe' 'Central City' 'Lake Park' 'Ste-Rose'
 'Saint-Jean-sur-Richelieu' 'Bolton' 'Dorval' 'Repentigny' 'Sainte-Thérèse'
 'Morin-Heights' 'Candiac' 'columbia station' 'Green Tree' 'Sharpsburg'
 'La Salle' 'Saint-Eustache' 'LaSalle' 'Boucherville' 'Lavaltrie' 'Vanier'
 'Crafton' 'tempe arizona' 'Noyan' 'Old Town' 'Vimont' 'Caledon Village'
 "L'ile-Bizard" 'Fairport Harbor' 'Leith' 'Balerno' 'Aberlady'
 'Musselburgh' 'Haddington' 'Lasswade' 'Gullane' 'Mascouche'
 'Mentor-on-the-Lake' 'Saint-Jean-Sur-Richelieu' 'Champlain' 'Kahnawake'
 'Moss' 'St-Jerome' 'St-Bruno-de-Montarville' 'Sainte-Catherine'
 'Mt. Oliver Boro' 'N Las Vegas' 'West Akron' 'AGINCOURT' 'Mentor On the'
 'Blainville' 'Montréal-Nord' 'Grafton' 'Sainte-Madeleine' 'East Cleveland'
 'Buena Vista' 'Fort  Mill' 'Anjou' 'Wesley Chapel' 'Filderstadt'
 'Lowesville' 'Bedford Hts.' 'Mount Albert' 'Saint-Constant' 'Chambly'
 'Nellis Afb' 'Sainte-Thérèse-de-Blainville' 'Farnham' 'McAdenville'
 'Caledon East' 'Mc Farland' 'Brunswick Hills' 'Nellis AFB'
 'Bradford West Gwillimbury' 'Munroe Falls' 'South Mountain'
 'Lower Burrell' 'Fabreville' 'Kirtland' 'Brookpark'
 'Salaberry-De-Valleyfield' 'Peninsula' 'Rigaud' 'Saint-Jérôme'
 'Sainte-Anne-De-Bellevue' 'Godmanchester' 'Ormstown' 'Rawdon'
 'Sainte-Dorothée' 'Brooklin' 'Mississuaga' 'Mentor On the Lake' 'Higley'
 'Sheffield Lake' 'Harwick' 'Forest Hills' 'Indian Lands' 'Baldwin'
 'Harrison City' 'Millvale' 'Malton' 'Wilkinsburg' 'Edimbourg' 'South Park'
 'Remseck' 'Olmsted Township' 'Schönaich' 'Hemmingen' 'King' 'Schwaikheim'
 'Broadview Heights' 'Stowe' 'Kernen' 'Saint Joseph' 'Mc Donald'
 'East Pittsburgh' 'Korntal-Münchingen' 'Dalkeith' 'Glasgow' 'Swissvale'
 'McMasterville' 'Mc Murray' 'Cote-Saint-Luc' 'Stoney Creek' 'Ranlo'
 'Pointe-Aux-Trembles' 'Warrensville Hts.' 'Peters Township' 'Gates Mills'
 'Beeton' 'Montreal-West' 'Montreal-Nord' 'East Liberty' 'N Ridgeville'
 'Castle Shannon' 'Shorewood Hills' 'Mesa AZ' 'Inverkeithing' 'Dravosburg'
 'Huntingdon' 'Las vegas' 'Gorebridge' 'Dunfermline' 'Prestonpans'
 'Belleville' 'Saint-Pierre-de-Véronne-à-Pike-River' 'La Baie'
 "L'assomption" 'Beaconsfield' 'Sainte-Therese' 'Rosemère'
 'Saint-Bruno-de-Montarville' 'Stockbridge' 'Steinenbronn' 'Kernen-Stetten'
 'Hochdorf' 'Möglingen' 'Neuhausen' 'Wolfschlugen' 'Kernen im Remstal'
 'Remseck am Neckar' 'Saint-Sauveur-des-Monts' 'Port Credit' 'Moon Twp'
 'Lower Lawrenceville' "L'Île-Perrôt" 'Delson' 'Tranent' 'Chatauguay'
 'Morgan' 'Saint-sauveur' 'Indianola' 'Nobleton' 'Aspinwall'
 'Summerlin South' 'Auburn Township' 'Brookline' 'King City' 'Kleinburg'
 'NORTH YORK' 'Plieningen' 'Tolono' 'McFarland' 'Sainte-Adele' 'Avalon'
 'Ahwatukee' 'Communauté-Urbaine-de-Montréal' 'Bonnyrigg and Lasswade'
 'Loanhead' "Baie-D'urfe" 'Mint  Hill' 'Saint-Basile-Le-Grand' 'Russell'
 'N. Olmsted' 'Stowe Township' 'Heidelberg' 'Bath' 'Sindelfingen/Eichholz'
 'Juniper Green' 'Berg' 'Moreland Hills' 'Freyburg' nan 'Ste-Adele'
 'Thornhil' 'toronto' 'Mattews' 'Regional Municipality of York'
 'Sainte-thérèse' 'Mount Royal' 'Cote Saint-Luc'
 'Le Haut-Saint-Laurent Regional County Municipality' 'Cramond'
 'Oak Ridges' 'Paradise' 'Robinson' 'Leetsdale' 'Sagamore Hills'
 'Enterprise' 'Fox Chapel' 'Dollard-Des Ormeaux' 'Squirrel Hill'
 'Pepper Pike' 'Saint-Lazare' 'Pitcairn' 'Villa Grove' 'Bellvue' 'Ross'
 "L'ile-Perrot" 'Schomberg' 'Cuyahoga Fls' 'Ste-Therese-de-Blainville'
 'Montréal-Ouest' 'Litchfield' 'Maple Grove' 'Pincourt' 'Canonsburd'
 'McKnight' 'Hiram' 'Mount Washington' 'North Huntington'
 'Northfield Center' 'East Mc Keesport' 'Crescent' 'las vegas' 'Mooers'
 'Churubusco' 'Camargo' 'Île-des-Soeurs' 'North Randall' 'Missisauga'
 'Las  Vegas' 'Oka' 'Glenrothes' 'Tottenham' 'Queensferry' 'Newbridge'
 'Bois-Des-Filion' 'Regent Square' 'Prévost' 'Upper St Clair'
 'Concord Mills' 'St Leonard' 'Freiberg']
--------------------------------------------------------------------------------
is_open                        2
[0 1]
--------------------------------------------------------------------------------
latitude                       30500
[ 33.381279   33.319526   43.8414527 ...,  55.9521955  41.483414
  33.4213255]
--------------------------------------------------------------------------------
longitude                      30536
[-111.724168  -111.925763   -79.0839962 ...,   -3.2031237  -81.769703
 -111.8932437]
--------------------------------------------------------------------------------
name                           22620
["Rania's Kabob Grill" 'Zaytoon Kabob Bistro' 'Mahipar Kabab' ...,
 'La Perle Noire' 'Chaophraya Edinburgh' 'Prog Gastro Lounge']
--------------------------------------------------------------------------------
neighborhood                   331
[nan 'Scarborough' 'Willowdale' 'Cooksville' 'Dollard-des-Ormeaux'
 'Capitol' 'Etobicoke' 'Summerlin' 'Entertainment District' 'The Danforth'
 'Westside' 'Southeast' 'Laval' 'Plateau-Mont-Royal' 'Erin Mills'
 'Rosemont-La Petite-Patrie' 'East Credit' 'Newington' 'Box Grove'
 'Yonge and Eglinton' 'Lisgar' 'Hanlan' 'Little Italy' 'Schenk - Atwood'
 'Bloomfield' 'Alexandra Park' 'Christie Pits' 'Tollcross' 'Eastland'
 'Bloordale Village' 'NoDa' 'Dovercourt' 'Haymarket' 'Bruntsfield'
 'Greektown' 'New Town' 'Ville-Marie' 'Mercier-Hochelaga-Maisonneuve'
 'Notre-Dame-de-Grâce' 'Côte-des-Neiges' 'Discovery District' 'Niagara'
 'Sud-Ouest' 'East York' 'Arboretum' 'Jefferson' 'Downtown Core'
 'Steele Creek' 'Downtown' 'Financial District' 'Cotswold' 'Chinatown'
 'South Summerlin' 'Oakland' 'South Side' 'The Strip' 'Sewickley'
 'University City' 'Plaza Midwood' 'Biddleville' 'First Ward'
 'Duquesne Heights' 'Unionville' 'Parkdale' 'Williamson - Marquette'
 'Ossington Strip' 'South End' 'Greentree' 'Shadyside' 'Gateway District'
 'Homestead' 'Tremont' 'The Annex' 'Ballantyne' 'Fourth Ward' 'Riverdale'
 'Mount Pleasant and Davisville' 'Warehouse District' 'East Bank'
 'Ohio City' 'East Liberty' 'Yonge and St. Clair' 'Mayfair Park' 'Uptown'
 'South Park' 'Civic Center' 'Anthem' 'Church-Wellesley Village'
 'University' 'Elizabeth' 'Bellevue' 'Eastside' 'Corktown' 'Spring Valley'
 'Old Town' 'Liberty Village' 'Southwest' 'Northeast District' 'LaSalle'
 'Northwest' 'Friendship' 'The Lakes' 'Yorkville' 'North Side' 'Centennial'
 'Dudgeon-Monroe' 'Kensington Market' 'Highland Creek' 'Lawrenceville'
 'South Hill' 'Tenney - Lapham' 'St. Lawrence' 'Sharpsburg' 'Carrick'
 'Banksville' 'Aspinwall' 'Langstaff' 'Ryerson' 'Emsworth' 'Squirrel Hill'
 'North Charlotte' 'Playhouse Square' 'High Park' 'Goodrich Kirtland'
 'Little Portugal' 'Bayview Village' 'North Collinwood' 'Leslieville'
 'Whiskey Island' 'Fairfax' 'Cascade Crossing' 'Central'
 'South Side Slopes' 'Edgeley' 'Cabbagetown' 'Kinsman' 'Avalon' 'Burr Oaks'
 'Regent' 'Brossard' 'The Beach' 'Sunrise' 'Quadrangle' 'Dilworth'
 'Rosedale' 'McClellan Park' 'Swansea' 'Eastmorland' 'Strip District'
 'Edgewater' 'Bluff Acres' 'Detroit-Shoreway' 'Derita' 'South Broadway'
 'Garfield' 'Paw Creek' 'Mont-Royal' 'Dufferin Grove' 'Lake Edge'
 'Pine Grove' 'Starmount' 'Villeray-Saint-Michel-Parc-Extension'
 'Downsview' 'Kirkland' 'Wexford' 'The Junction' 'Streetsville'
 'Brockton Village' 'Old Brooklyn' 'Sherman' 'West View' 'Homewood'
 'West Boulevard' 'Port Credit' 'Thornhill Woods' 'Concord' 'Clark-Fulton'
 'Hough' 'Summerville' 'West Queen West' 'Bickford Park' 'Harbourfront'
 'Millvale' 'Third Ward' 'Eken Park' 'Verdun' 'Greenfield' 'Pointe-Claire'
 'Saint-Laurent' 'Upper Beach' 'Clarkson' 'Rockwood Village' 'Leopold'
 'High Crossing' 'Northeast Shores' 'Etna' 'Milliken'
 'Ahunstic-Cartierville' 'Brooklyn-Centre' 'Puritas-Longmead' 'Carnegie'
 'Highland Park' 'Myers Park' 'Dixie' 'Forrest Hill' 'Overbrook'
 "Bram's Addition" 'Regent Square' 'Cudell' 'Wychwood' 'Greensborough'
 'Dormont' 'Sedgefield' 'West End' 'Riverside' 'Stockbridge' 'Bay Creek'
 'East 185th' 'Koreatown' 'Saint-Léonard' 'Junction Ridge'
 'Queen Street West' 'Bloor-West Village' "Brown's Corners" 'Buttonville'
 'Outremont' 'Greenbush' 'Tower City' 'Montréal-Ouest' 'Maple'
 'Trinity Bellwoods' 'Hawthorne' 'Old Malton Village' 'Thornhill'
 'Markham Village' 'Beaconsfield Village' 'Leith' 'The Meadows'
 'South Campus' 'Palmerston' 'Seaton Village' 'Ile-Perrot'
 'The Hill District' 'Brookline' 'Elvehjem' 'South Collinwood'
 'University of Toronto' 'Vilas' 'Burnhamthorpe' 'Pierrefonds-Roxboro'
 'Lachine' 'Vaudreuil-Dorion' 'Point Breeze' 'Summer Hill' 'Corso Italia'
 'Royal Mile' 'Dorval' 'Meadowvale Village' 'Sherwood Forest'
 'Roncesvalles' 'Morningside' 'Emerson East' 'Allentown' 'Montréal-Nord'
 'Distillery District' 'Wallace Emerson' 'Ile-Bizard-Sainte-Genevieve'
 'Erindale' 'Marchmont' 'Cannonmills' 'Bon Air' 'Mississauga Valley'
 'Malton' 'Knoxville' 'City Place' 'Anjou' 'Worthington Park'
 'East Cleveland' 'Heistand' 'Beechview' 'Kleinburg' 'Westchester Gardens'
 'Woodbridge' 'Rivière-des-Prairies–Pointe-aux-Trembles' 'Lorne Park'
 'Westmount' 'Larimer' 'Euclid-Green' 'Rolling Meadows' 'Mt. Oliver'
 'Maple - Prairie' 'Stockyards' 'St Clair-Superior' 'Troy Hill'
 'Brighton Heights' 'Starkweather - Yahar' 'Villa Heights' 'The Flats'
 'Mt. Washington' 'North Broadway' "Allied Dunn's Marsh" 'Norman Acres'
 'Meadowood' 'Côte Saint-Luc' '200th Street' 'Maple Wood' 'Summit Woods'
 'Ridge & Memphis' 'Stone Meadows' 'Lakeview' 'Sauk Creek' 'Beaconsfield'
 'Hazelwood' 'Casa Loma' 'Sunset Village' 'Oakbridge Community' 'Birchwood'
 'West Bank' 'Midvale Heights Community' 'Sainte-Anne-de-Bellevue'
 'Westmorland' 'Hampstead' 'Brooklyn Acres' 'Altstadt' 'Spring Harbor'
 'Glendale' 'East Carnegie' 'West Don Lands' 'Observatory Hill'
 'Westhaven Trails' 'Highland']
--------------------------------------------------------------------------------
postal_code                    7175
['85234' '85226' 'L1V 1C1' ..., 'H3H 2P1' 'M5H 1Z4' 'J4V 3N2']
--------------------------------------------------------------------------------
review_count                   750
[ 320    3    6   13   15   39    4   20    5   12   33   18   74   67   47
    7   78  101   21  122   23  157  161   62  103   52   65    9   31    8
   46  224   57   25   50  222   11  106  111   61   14   22  173   54   10
   36   44   28   17   27   42   26   88   30  140   24   16   58   89   45
   80   19   53   34  289   37  109   66  117  150   60  276  167  268  148
   83  314  418   41   69  338   82  168  377   29  215  112  244  930   93
  162  236   32   59   48  196  126   38  206  243   72   49  137   92  125
  144  617 1817  114  127  780  266   81  372  827   55  245  326  214   43
  223  656  278   35  468   63  632  264  153   94  528   64  493   95 1006
  225  233  287   97  291  116   79  123  135  120  124  795  100   75  253
  166  194  175   40  143  262  110  237  170  193  204   87  256  693   77
   98  571  337   90  251   76   84  146  389  458  219   68  158  172  304
  154  660   85 1066  108   71  461  138  211  378   70  177  515   56  315
  160  189   91  306   51  327  107  176  184  197  104  845  948 2909  424
  391  370  259  199  286  186  353  311  485  416  279  312  388  486  575
  323  192  333  248  118  164  667  307  191  141  318  208  226   73  539
  475  469  151  247  179  726  149  429  638  535  386  310  159   99 1884
  604  965  355  136 4371  129  105  180  190  241  130  592  831  195  298
   86  231  497  294   96  890  540  155  238  746  619  254  864  188 1185
 2698  425  212  203  841  398  724  366  368  514  305  156  299 2385  205
  317  848  444  445  696  121  169  290  239  564  301  986  588  367  758
  113  230  650  229  394  472 2963  209  267  585  350  759  351  507 1042
  147  246  421  202  240  465  145  409  896  119  242  163  381 1058  362
  374  216 3700  406  687  508  678  272  288  646  360  723  470  207  330
  132  255  115  335  572  250  441  313  459  371  187  828  882 1128  265
  352  622  589  602  365  228  297  596  390  270  346  134  325  599  823
  285  128 1122  263  178  221 5429  689  436  880  431  961  165  220  185
  102  200  772  142 1468  518 1292  363  183  302  669 1057  715  426  182
 1549  232  686  361  322  281 1097  499  456  448  402  273  181  234  763
  213  413  133  771  376  235  720  139  506 2345  210  218  293  439  227
  198  878  744  131  434  626  598  500  384  504 1168 1063  284  510  450
  907  682 1080  258  341  708  375  863 1262  558  269  583 3180  300  336
  502  594 1226  321  430  382  171  832  908  152  344  768  455  414  316
  898 1244  174  637  343 1131  552  443  385 1319  332  408  358  387  345
  295  566 1221  607  888 2177  380  201  392  950  340  577 1523  280  481
  892 1712  894  680  257 2012  334  324  271  956  261  249 1398  296  308
  618  700 5632 1630  432  404  711 6979  464  217  739  319  467  356  275
  274  277 1348  887  620  542  743  457  967  576 1834  503  820  554 3873
  523  732  569  633  767  561 1054  419  786  339  411 1389  545  331  826
  342  625  883  509  982  359  407  422  749  479  488  491  417  369  373
  579  462  427  505  719  420  329  428  401 2445  494  595  260  729  454
  685  354  538  970  755 1241  364  877  574 1145  498  591  517  383  983
  492  357  489  520  451  889  328  471  379  309  661 1067  252  590  610
  553  483  745  568 1116  698  703  593  283  446  707 1025 1899 1602 2123
  725  397  935  435  658  761  814  899  533  581 1349  400  282  702 2151
 1099  348  647  942  559  794  586  410  912  433  998  754  810 1609  994
  440  550  303  453  570  897  615  783  449  557 1264  891  838  613  560
  522 2185  716  477  706  628  393  701 3542  547  642 1610  738  853  885
  541  855  403  549  621  984  824  563 1665  659  778  721  822  452 1309
  405 1534 1180  866 1150  634  347 1404  478  623 1300  531  939 1648  512]
--------------------------------------------------------------------------------
stars                          9
[ 4.   3.5  3.   2.5  4.5  5.   1.5  2.   1. ]
--------------------------------------------------------------------------------
state                          31
['AZ' 'ON' 'QC' 'WI' 'OH' 'NV' 'NC' 'EDH' 'BW' 'PA' 'MLN' 'IL' 'SC' 'NY'
 'HLD' 'FIF' 'ESX' 'WLN' 'C' '3' 'BY' 'ELN' 'NYK' '01' 'ZET' 'NI' 'WHT'
 'PKN' 'ST' 'HH' 'CA']
--------------------------------------------------------------------------------
monday_open                    48
['11:00:00' nan '12:00:00' '10:00:00' '11:30:00' '17:00:00' '07:30:00'
 '10:30:00' '15:00:00' '14:00:00' '16:00:00' '09:00:00' '08:00:00'
 '17:30:00' '12:30:00' '16:30:00' '05:00:00' '06:00:00' '07:00:00'

saturday_close                 62
['22:00:00' nan '02:00:00' '23:00:00' '00:00:00' '20:00:00' '21:00:00'
 '21:30:00' '22:30:00' '23:30:00' '01:00:00' '20:30:00' '15:00:00'
 '02:30:00' '18:00:00' '19:00:00' '03:00:00' '04:00:00' '20:45:00'
 '14:00:00' '01:30:00' '16:00:00' '12:00:00' '17:00:00' '19:30:00'
 '14:30:00' '05:00:00' '06:00:00' '08:00:00' '00:30:00' '22:15:00'
 '16:30:00' '11:00:00' '23:45:00' '05:30:00' '13:00:00' '15:30:00'
 '17:30:00' '12:30:00' '04:30:00' '10:30:00' '13:30:00' '11:15:00'
 '23:59:00' '18:30:00' '22:45:00' '03:30:00' '06:30:00' '09:00:00'
 '07:00:00' '01:45:00' '08:30:00' '03:59:00' '21:45:00' '23:15:00'
 '01:10:00' '10:00:00' '11:30:00' '02:45:00' '15:45:00' '03:45:00'
 '00:45:00']
--------------------------------------------------------------------------------
sunday_open                    50
['11:00:00' nan '16:00:00' '11:30:00' '12:00:00' '13:00:00' '17:00:00'
 '08:00:00' '14:00:00' '15:00:00' '10:00:00' '18:00:00' '17:30:00'
 '06:30:00' '12:30:00' '16:30:00' '05:00:00' '06:00:00' '00:00:00'
 '10:30:00' '09:00:00' '07:00:00' '09:30:00' '08:30:00' '19:00:00'
 '07:30:00' '05:30:00' '10:45:00' '04:30:00' '18:30:00' '23:00:00'
 '00:30:00' '22:30:00' '03:00:00' '20:00:00' '01:00:00' '23:30:00'
 '14:30:00' '15:30:00' '21:30:00' '09:45:00' '11:45:00' '02:00:00'
 '11:15:00' '04:00:00' '13:30:00' '08:15:00' '12:15:00' '22:00:00'
 '06:45:00']
--------------------------------------------------------------------------------
sunday_close                   60
['21:00:00' nan '22:00:00' '00:00:00' '20:00:00' '21:30:00' '20:30:00'
 '23:00:00' '22:30:00' '23:30:00' '18:00:00' '15:00:00' '02:00:00'
 '19:00:00' '01:00:00' '03:00:00' '17:00:00' '20:45:00' '14:00:00'
 '14:30:00' '01:30:00' '16:00:00' '13:00:00' '19:30:00' '12:30:00'
 '05:00:00' '06:00:00' '04:00:00' '16:30:00' '17:30:00' '00:30:00'
 '15:30:00' '12:00:00' '22:15:00' '13:30:00' '11:00:00' '02:30:00'
 '05:30:00' '04:30:00' '10:30:00' '23:59:00' '18:30:00' '09:00:00'
 '23:45:00' '07:00:00' '01:45:00' '08:30:00' '03:30:00' '01:10:00'
 '21:45:00' '22:45:00' '11:30:00' '00:45:00' '00:15:00' '18:45:00'
 '15:45:00' '10:00:00' '19:45:00' '02:45:00' '03:59:00']
--------------------------------------------------------------------------------
alcohol                        4
['beer_and_wine' nan 'none' 'full_bar']
--------------------------------------------------------------------------------
ambience_casual                3
[True nan False]
--------------------------------------------------------------------------------
ambience_classy                3
[False nan True]
--------------------------------------------------------------------------------
ambience_divey                 3
[False nan True]
--------------------------------------------------------------------------------
ambience_hipster               3
[False nan True]
--------------------------------------------------------------------------------
ambience_intimate              3
[False nan True]
--------------------------------------------------------------------------------
ambience_romantic              3
[False nan True]
--------------------------------------------------------------------------------
ambience_touristy              3
[False nan True]
--------------------------------------------------------------------------------
ambience_trendy                3
[False nan True]
--------------------------------------------------------------------------------
ambience_upscale               3
[False nan True]
--------------------------------------------------------------------------------
byob                           3
[ nan   0.   1.]
--------------------------------------------------------------------------------
byobcorkage                    4
[nan 'no' 'yes_corkage' 'yes_free']
--------------------------------------------------------------------------------
bestnights_friday              3
[nan True False]
--------------------------------------------------------------------------------
bestnights_monday              2
[nan False]
--------------------------------------------------------------------------------
bestnights_saturday            3
[nan True False]
--------------------------------------------------------------------------------
bestnights_sunday              3
[nan True False]
--------------------------------------------------------------------------------
bestnights_thursday            2
[nan False]
--------------------------------------------------------------------------------
bestnights_tuesday             2
[nan False]
--------------------------------------------------------------------------------
bestnights_wednesday           2
[nan False]
--------------------------------------------------------------------------------
bikeparking                    3
[  1.  nan   0.]
--------------------------------------------------------------------------------
businessacceptsbitcoin         3
[ nan   0.   1.]
--------------------------------------------------------------------------------
businessacceptscreditcards     3
[  1.  nan   0.]
--------------------------------------------------------------------------------
businessparking_garage         3
[False nan True]
--------------------------------------------------------------------------------
businessparking_lot            3
[True nan False]
--------------------------------------------------------------------------------
businessparking_street         3
[False nan True]
--------------------------------------------------------------------------------
businessparking_valet          3
[False nan True]
--------------------------------------------------------------------------------
businessparking_validated      3
[False nan True]
--------------------------------------------------------------------------------
caters                         3
[  1.  nan   0.]
--------------------------------------------------------------------------------
coatcheck                      2
[ nan   0.]
--------------------------------------------------------------------------------
corkage                        3
[ nan   1.   0.]
--------------------------------------------------------------------------------
dietaryrestrictions_dairy-free 3
[nan False True]
--------------------------------------------------------------------------------
dietaryrestrictions_gluten-free 3
[nan False True]
--------------------------------------------------------------------------------
dietaryrestrictions_halal      3
[nan False True]
--------------------------------------------------------------------------------
dietaryrestrictions_kosher     3
[nan False True]
--------------------------------------------------------------------------------
dietaryrestrictions_soy-free   3
[nan False True]
--------------------------------------------------------------------------------
dietaryrestrictions_vegan      3
[nan False True]
--------------------------------------------------------------------------------
dietaryrestrictions_vegetarian 3
[nan False True]
--------------------------------------------------------------------------------
dogsallowed                    3
[  0.  nan   1.]
--------------------------------------------------------------------------------
drivethru                      3
[ nan   0.   1.]
--------------------------------------------------------------------------------
goodfordancing                 2
[ nan   0.]
--------------------------------------------------------------------------------
goodforkids                    3
[  1.  nan   0.]
--------------------------------------------------------------------------------
goodformeal_breakfast          3
[False nan True]
--------------------------------------------------------------------------------
goodformeal_brunch             3
[False nan True]
--------------------------------------------------------------------------------
goodformeal_dessert            3
[False nan True]
--------------------------------------------------------------------------------
goodformeal_dinner             3
[True nan False]
--------------------------------------------------------------------------------
goodformeal_latenight          3
[False nan True]
--------------------------------------------------------------------------------
goodformeal_lunch              3
[True nan False]
--------------------------------------------------------------------------------
happyhour                      2
[ nan   1.]
--------------------------------------------------------------------------------
hastv                          3
[  1.   0.  nan]
--------------------------------------------------------------------------------
music_background_music         3
[nan True False]
--------------------------------------------------------------------------------
music_dj                       2
[nan False]
--------------------------------------------------------------------------------
music_jukebox                  2
[nan False]
--------------------------------------------------------------------------------
music_karaoke                  2

[nan False]
--------------------------------------------------------------------------------
music_live                     2
[nan False]
--------------------------------------------------------------------------------
music_no_music                 2
[nan False]
--------------------------------------------------------------------------------
music_video                    2
[nan False]
--------------------------------------------------------------------------------
noiselevel                     5
['average' nan 'quiet' 'loud' 'very_loud']
--------------------------------------------------------------------------------
open24hours                    3
[ nan   0.   1.]
--------------------------------------------------------------------------------
outdoorseating                 3
[  0.   1.  nan]
--------------------------------------------------------------------------------
restaurantsattire              4
['casual' nan 'dressy' 'formal']
--------------------------------------------------------------------------------
restaurantscounterservice      3
[ nan   0.   1.]
--------------------------------------------------------------------------------
restaurantsdelivery            3
[  1.  nan   0.]
--------------------------------------------------------------------------------
restaurantsgoodforgroups       3
[  1.   0.  nan]
--------------------------------------------------------------------------------
restaurantspricerange2         5
[  2.   1.  nan   4.   3.]
--------------------------------------------------------------------------------
restaurantsreservations        3
[  1.   0.  nan]
--------------------------------------------------------------------------------
restaurantstableservice        3
[  1.  nan   0.]
--------------------------------------------------------------------------------
restaurantstakeout             3
[  1.  nan   0.]
--------------------------------------------------------------------------------
smoking                        2
[nan 'no']
--------------------------------------------------------------------------------
wheelchairaccessible           3
[  1.  nan   0.]
--------------------------------------------------------------------------------
wifi                           4
['free' nan 'no' 'paid']
--------------------------------------------------------------------------------

<p><b>4.</b> Number of locations grouped by name</p>

In [80]:
tmp = restaurants.groupby('name').count()['business_id'].to_frame()
tmp = tmp[tmp.business_id > 1]
tmp.sort_values(['business_id'], ascending=False)[:20]

                                 business_id
name
McDonald's                               618
Subway                                   578
Taco Bell                                276
Pizza Hut                                269
Burger King                              247
Wendy's                                  228
Chipotle Mexican Grill                   164
Domino's Pizza                           160
KFC                                      140
Panda Express                            123
Papa John's Pizza                        118
Arby's                                   115
Popeyes Louisiana Kitchen                107
Denny's                                   94
Five Guys                                 82
Jack in the Box                           80
Jersey Mike's Subs                        76
Firehouse Subs                            68
Swiss Chalet Rotisserie & Grill           65
IHOP                                      65